server:
  port: 8081
  servlet:    context-path: /oauth2

spring:   application:    name: Oauth2Server  datasource:    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver      jdbc-url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&transformedBitIsBoolean=true&allowPublicKeyRetrieval=true
      username: root
      password: root
      connection-test-query: SELECT 1
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 3000      