spring:
  redis:    host: 127.0.0.1
    port: 6379
    jedis:      pool:
                    # 连接池最大连接数（使用负值表示没有限制）        max-active: 10000
                    # 连接池中的最大空闲连接
        max-idle: 1000
        min-idle: 100 
                    # 连接池最大阻塞等待时间，单位是毫秒（使用负值表示没有限制）
        max-wait: 10000
                    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs: 60000